---
extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
  - 2
  - always
  - - chore
    - feat
    - fix
    - refactor
    - perf
    - test
    - revert
help: |
  **Possible types**:
  `ci`:       Changes to our CI configuration files and scripts
  `feat`:     Adds a new feature.
  `fix`:      Solves a bug.
  `refactor`: Rewrites code without feature, performance or bug changes.
  `perf`:     Improves performance.
  `test`:     Adds or modifies tests.
  `revert`:   Changes that reverting other changes
