name: Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'ephemeralTwitter/**'
      - 'handler.go'
      - 'host.json'
      - 'proxies.json'
      - 'go.mod'
      - 'go.sum'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: |
        cd src
        go build handler.go -o ../handler.exe
        cd ..
    - name: Deploy
      uses: Azure/functions-action@v1
      with:
        app-name: ephemeral-twitter
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true
