on: [pull_request]

name: Validate Code
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Golang CI
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        working-directory: src
    - name: Unit Tests
      run: go test . -v
